name: Continous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Python Black Check
        uses: RojerGS/python-black-check@1.0.1
        with:
          path: '../../'  
