name: Code Check (Black, iSort)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
                    
      - name: Run Test and Commit Changes to the pull request, if needed
        run: |
          git config --global user.name 'autoblack'
          git config --global user.email 'autoblack@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout $GITHUB_HEAD_REF
          echo '----isort----'
          pip install isort
          isort .
          echo '----black----'
          pip install black
          black .
          git commit -am "FIX: Auto-Format Python code"
          git push
               
