name: Continous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python Black Check
        uses: RojerGS/python-black-check@1.0.1
        with:
          # File or directory to run black on.
          path: . # optional, default is .
          # The number of characters allowed per line.
          line-length: '81' # optional, default is 81
