name: Code Check (Black)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run Black Check
        run: |
          pip install black
          black --check .
      - name: Commit Black changes to the pull request, if needed
        if: failure()
        run: |
          git config --global user.name 'autoblack'
          git config --global user.email 'autoblack@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout $GITHUB_HEAD_REF
          black .
          git commit -am "FIX: Auto-Format Python code with Black"
          git push
      - name: Run iSort Check
        run: |
          pip install isort
          isort --check .
      - name: Commit Black changes to the pull request, if needed
        if: failure()
        run: |
          git config --global user.name 'autoblack'
          git config --global user.email 'autoblack@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout $GITHUB_HEAD_REF
          black .
          git commit -am "FIX: Auto-Format Python code with iSort"
          git push
      
