name: Continous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run Black
        run: |
          pip install black
          black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
          git config --global user.name 'autoblack'
          git config --global user.email 'sunnywent2texas@users.noreply.github.com'
          run: echo 'hallo'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          run: echo 'REPO sonja' $GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          run: echo 'HEAD REF sonja' $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          run: echo 'commit'
          git push
          run: echo 'push'
