name: Code Check (Black, iSort)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: Run Checks (Black, iSort)
        run: |
          echo '------iSort------------'
          pip install isort
          isort --check .
          echo '------Black------------'
          pip install black
          black --check .
          
      - name: Commit Changes to the pull request, if needed
        if: failure()
        run: |
          git config --global user.name 'autoblack'
          git config --global user.email 'autoblack@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch
          git checkout $GITHUB_HEAD_REF
          isort .
          black .
          git commit -am "FIX: Auto-Format Python code with Black/iSort"
          git push
      
      
